### ISSUE TITLE
Contingency Table Error

### ISSUE THREAD

**Issue by Caealana** [discdiver/intro-data-capstone-musclehub#3]
https://github.com/discdiver/intro-data-capstone-musclehub/blob/1d73e699c381578fcf440fe8c416022c5ff484fa/MuscleHub%20Project%20File%20Jeff%20Hale%20Codecademy/musclehub%20jupyter%20python%20notebook%20jeff%20hale.py#L327

It looks like the second/right column of your contingency table uses the sums of the Member and Not Member counts for groups A and B instead of using just the Not Member counts.
Your contingency table should look like the following:
<img width="195" alt="screenshot at feb 13 13-20-05" src="https://user-images.githubusercontent.com/14001120/36163726-9f5253b4-10c0-11e8-86d1-daaec4b8ec8c.png">

`contingency = [[200, 50], [250, 75]]`

**Comment by discdiver** [comment]
Thank you for the feedback, Caealana!

**Comment by discdiver** [comment]
I made this correction.
